
import type { Category, Product } from './types';
import { TractorIcon, CowIcon, WheatIcon, PersonIcon, FieldIcon } from './src/components/IconComponents';

export const CATEGORIES: Category[] = [
  { id: 'maquinaria', name: 'Maquinaria', icon: TractorIcon },
  { id: 'ganaderia', name: 'Ganadería', icon: CowIcon },
  { id: 'insumos', name: 'Insumos', icon: WheatIcon },
  { id: 'profesionales', name: 'Profesionales', icon: PersonIcon },
  { id: 'inmobiliaria', name: 'Inmobiliaria', icon: FieldIcon },
];

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Tractor John Deere 6110J',
    description: 'Excelente estado, 4x4, con pala frontal. Listo para trabajar. Pocas horas de uso.',
    price: 85000,
    currency: 'USD',
    location: 'Córdoba Capital',
    province: 'Córdoba',
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Maquinaria',
    subcategory: 'Tractores',
    isSponsored: true,
    isPremium: true,
    userType: 'premium-empresa',
    tags: ['tractor', 'john deere', '4x4', 'pala frontal'],
    approvalStatus: 'approved',
    scrapingSource: 'mercadolibre',
    updatedAt: new Date('2025-11-15').toISOString(),
  },
  {
    id: '2',
    title: 'Vaquillonas Angus preñadas',
    description: 'Lote de 20 vaquillonas Angus coloradas y negras, preñadas por inseminación artificial.',
    price: 1500,
    currency: 'USD',
    location: 'Tandil',
    province: 'Buenos Aires',
    imageUrl: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Ganadería',
    subcategory: 'Bovinos',
    isSponsored: false,
    isPremium: true,
    userType: 'premium-particular',
    tags: ['vaquillonas', 'angus', 'ganado', 'preñadas'],
    approvalStatus: 'approved',
    scrapingSource: 'agrofy',
    updatedAt: new Date('2025-11-14').toISOString(),
  },
  {
    id: '3',
    title: 'Semillas de Soja Don Mario',
    description: 'Bolsa de semillas de soja de primera calidad, variedad resistente a sequía.',
    price: 200,
    currency: 'USD',
    location: 'Rosario',
    province: 'Santa Fe',
    imageUrl: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Insumos',
    subcategory: 'Semillas',
    isSponsored: false,
    isPremium: false,
    userType: 'free',
    tags: ['semillas', 'soja', 'don mario'],
    approvalStatus: 'approved',
    scrapingSource: 'agroads',
    updatedAt: new Date('2025-11-13').toISOString(),
  },
  {
    id: '4',
    title: 'Campo de 200 hectáreas en venta',
    description: 'Campo agrícola mixto, con excelentes rindes. Alambrado perimetral y aguadas.',
    price: 2000000,
    currency: 'USD',
    location: 'Santa Rosa',
    province: 'La Pampa',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Inmobiliaria',
    subcategory: 'Campos',
    isSponsored: true,
    isPremium: true,
    userType: 'premium-empresa',
    tags: ['campo', 'hectáreas', 'la pampa', 'venta'],
    approvalStatus: 'approved',
    scrapingSource: 'zonaprop',
    updatedAt: new Date('2025-11-16').toISOString(),
  },
  {
    id: '5',
    title: 'Cosechadora Case IH 8250',
    description: 'Modelo 2022 con plataforma de 40 pies. Mapeo y piloto automático. Muy cuidada.',
    price: 450000,
    currency: 'USD',
    location: 'Venado Tuerto',
    province: 'Santa Fe',
    imageUrl: 'https://images.unsplash.com/photo-1589066650834-eebd57c02c16?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Maquinaria',
    subcategory: 'Cosechadoras',
    isSponsored: false,
    isPremium: true,
    userType: 'premium-particular',
    tags: ['cosechadora', 'case', 'maquinaria', 'mapeo'],
    approvalStatus: 'approved',
    scrapingSource: 'mercadolibre',
    updatedAt: new Date('2025-11-12').toISOString(),
  },
  {
    id: '6',
    title: 'Asesoramiento agronómico',
    description: 'Servicios de consultoría para optimización de rindes y manejo de cultivos.',
    location: 'Rosario',
    province: 'Santa Fe',
    currency: 'ARS',
    imageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Profesionales',
    subcategory: 'Agronomía',
    isSponsored: false,
    isPremium: false,
    userType: 'free',
    tags: ['asesoramiento', 'agronomía', 'consultoría'],
    approvalStatus: 'approved',
    scrapingSource: 'agroempresarial',
    updatedAt: new Date('2025-11-11').toISOString(),
  },
  {
    id: '7',
    title: 'Toros Hereford Puros Registrados',
    description: 'Genética de punta para rodeos. Excelente desarrollo y sanidad garantizada.',
    price: 3000,
    currency: 'USD',
    location: 'Gualeguaychú',
    province: 'Entre Ríos',
    imageUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Ganadería',
    subcategory: 'Bovinos',
    isSponsored: true,
    isPremium: true,
    userType: 'premium-empresa',
    tags: ['toros', 'hereford', 'ganado', 'genética'],
    approvalStatus: 'approved',
    scrapingSource: 'agrofy',
    updatedAt: new Date('2025-11-15').toISOString(),
  },
  {
    id: '8',
    title: 'Fertilizante UREA granulada',
    description: 'Bolsas de 50kg. Ideal para maíz y trigo. Venta por mayor y menor.',
    price: 50,
    currency: 'USD',
    location: 'Villa María',
    province: 'Córdoba',
    imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Insumos',
    subcategory: 'Fertilizantes',
    isSponsored: false,
    isPremium: false,
    userType: 'free',
    tags: ['fertilizante', 'urea', 'insumos'],
    approvalStatus: 'approved',
    scrapingSource: 'agroads',
    updatedAt: new Date('2025-11-10').toISOString(),
  },
  {
    id: '9',
    title: 'Pulverizadora autopropulsada New Holland',
    description: 'Modelo 2020, 4000 litros, botalón de 36 metros, GPS y piloto automático.',
    price: 180000,
    currency: 'USD',
    location: 'Pergamino',
    province: 'Buenos Aires',
    imageUrl: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Maquinaria',
    subcategory: 'Pulverizadoras',
    isSponsored: true,
    isPremium: true,
    userType: 'premium-empresa',
    tags: ['pulverizadora', 'new holland', 'autopropulsada', 'gps'],
    approvalStatus: 'approved',
    scrapingSource: 'mercadolibre',
    updatedAt: new Date('2025-11-16').toISOString(),
  },
  {
    id: '10',
    title: 'Ovejas Hampshire Down',
    description: 'Lote de 100 ovejas de cabaña. Certificado de pedigree. Excelente lana.',
    price: 150,
    currency: 'USD',
    location: 'Bahía Blanca',
    province: 'Buenos Aires',
    imageUrl: 'https://images.unsplash.com/photo-1560594820-8be96c7f5f52?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Ganadería',
    subcategory: 'Ovinos',
    isSponsored: false,
    isPremium: true,
    userType: 'premium-particular',
    tags: ['ovejas', 'hampshire', 'lana', 'ganado'],
    approvalStatus: 'approved',
    scrapingSource: 'agrofy',
    updatedAt: new Date('2025-11-14').toISOString(),
  },
  {
    id: '11',
    title: 'Agroquímicos - Glifosato 66%',
    description: 'Bidones de 20 litros. Herbicida sistémico de amplio espectro. Stock permanente.',
    price: 120,
    currency: 'USD',
    location: 'Río Cuarto',
    province: 'Córdoba',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Insumos',
    subcategory: 'Agroquímicos',
    isSponsored: false,
    isPremium: false,
    userType: 'free',
    tags: ['agroquímicos', 'glifosato', 'herbicida'],
    approvalStatus: 'approved',
    scrapingSource: 'agroads',
    updatedAt: new Date('2025-11-13').toISOString(),
  },
  {
    id: '12',
    title: 'Chacra de 50 hectáreas - Zona productiva',
    description: 'Excelente ubicación, todos los servicios. Ideal para horticultura o ganadería.',
    price: 500000,
    currency: 'USD',
    location: 'San Pedro',
    province: 'Buenos Aires',
    imageUrl: 'https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Inmobiliaria',
    subcategory: 'Chacras',
    isSponsored: true,
    isPremium: true,
    userType: 'premium-empresa',
    tags: ['chacra', 'hectáreas', 'venta', 'productiva'],
    approvalStatus: 'approved',
    scrapingSource: 'zonaprop',
    updatedAt: new Date('2025-11-15').toISOString(),
  },
  {
    id: '13',
    title: 'Sembradora Crucianelli Air Drill',
    description: 'De 30 líneas a 17.5cm. Año 2018. Dosificador neumático, monitor de siembra.',
    price: 120000,
    currency: 'USD',
    location: 'Marcos Juárez',
    province: 'Córdoba',
    imageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Maquinaria',
    subcategory: 'Sembradoras',
    isSponsored: false,
    isPremium: true,
    userType: 'premium-particular',
    tags: ['sembradora', 'crucianelli', 'siembra directa'],
    approvalStatus: 'approved',
    scrapingSource: 'mercadolibre',
    updatedAt: new Date('2025-11-12').toISOString(),
  },
  {
    id: '14',
    title: 'Cabañas porcinas en producción',
    description: 'Sistema de cría intensiva. 200 madres en producción. Instalaciones modernas.',
    price: 800000,
    currency: 'USD',
    location: 'Esperanza',
    province: 'Santa Fe',
    imageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Ganadería',
    subcategory: 'Porcinos',
    isSponsored: true,
    isPremium: true,
    userType: 'premium-empresa',
    tags: ['porcinos', 'cerdos', 'cabaña', 'producción'],
    approvalStatus: 'approved',
    scrapingSource: 'agrofy',
    updatedAt: new Date('2025-11-16').toISOString(),
  },
  {
    id: '15',
    title: 'Alimento balanceado para bovinos',
    description: 'Bolsas de 50kg. Alto contenido proteico. Ideal para engorde a corral.',
    price: 35,
    currency: 'USD',
    location: 'Rafaela',
    province: 'Santa Fe',
    imageUrl: 'https://images.unsplash.com/photo-1500076656116-558758c991c1?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Insumos',
    subcategory: 'Alimentos',
    isSponsored: false,
    isPremium: false,
    userType: 'free',
    tags: ['alimento', 'balanceado', 'bovinos', 'engorde'],
    approvalStatus: 'approved',
    scrapingSource: 'agroads',
    updatedAt: new Date('2025-11-11').toISOString(),
  },
  {
    id: '16',
    title: 'Servicio de transporte de hacienda',
    description: 'Jaulas con capacidad de 24 animales. Cobertura en toda la zona pampeana.',
    location: 'General Pico',
    province: 'La Pampa',
    currency: 'ARS',
    imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Profesionales',
    subcategory: 'Transporte',
    isSponsored: false,
    isPremium: false,
    userType: 'free',
    tags: ['transporte', 'hacienda', 'camión', 'jaula'],
    approvalStatus: 'approved',
    scrapingSource: 'agroempresarial',
    updatedAt: new Date('2025-11-10').toISOString(),
  },
  {
    id: '17',
    title: 'Mixer para alimentación',
    description: 'Mixer vertical de 12m3. Ideal para feedlot. Balanza electrónica incorporada.',
    price: 45000,
    currency: 'USD',
    location: 'Armstrong',
    province: 'Santa Fe',
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Maquinaria',
    subcategory: 'Implementos',
    isSponsored: false,
    isPremium: true,
    userType: 'premium-particular',
    tags: ['mixer', 'alimentación', 'feedlot', 'balanza'],
    approvalStatus: 'approved',
    scrapingSource: 'mercadolibre',
    updatedAt: new Date('2025-11-13').toISOString(),
  },
  {
    id: '18',
    title: 'Estancia de 5000 hectáreas',
    description: 'Campo mixto ganadero-agrícola. Casco con 8 habitaciones. Instalaciones completas.',
    price: 8000000,
    currency: 'USD',
    location: 'Azul',
    province: 'Buenos Aires',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
    sourceUrl: '#',
    category: 'Inmobiliaria',
    subcategory: 'Estancias',
    isSponsored: true,
    isPremium: true,
    userType: 'premium-empresa',
    tags: ['estancia', 'campo', 'ganadería', 'agricultura'],
    approvalStatus: 'approved',
    scrapingSource: 'zonaprop',
    updatedAt: new Date('2025-11-16').toISOString(),
  },
];
