// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Cargar variables de entorno desde .env.local
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Usar DIRECT_URL para introspección (puerto 5432)
    url: process.env["DIRECT_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
